### ISSUE TITLE
Excellent!

### ISSUE THREAD

**Issue by gessel** [moudsen/mailGraph#22]
Would be lovely to have integrated into the API.  This is a really nice feature.

**Comment by moudsen** [comment]
Well, I've tried to get it into the API, but no luck up till now. Side tracking code next to the API as such to mimic the behavior.
I'm pulling the code to generate graphs wihtin the next weeks or so for anyone to add this functionality to any type of code.

**Comment by moudsen** [comment]
Following up in #14

**Comment by splitice** [comment]
Personally I think theres some interesting possiblities for authentication control and in keeping the data up to date with direct linking into the zabbix graphs.

However it's slightly thwarted  by many mail clients not having configurable trusted URLs to allow direct fetching...

GSuite looks to be leading the way here with the ability to exclude the image from "proxying" (short term cache) and with a relatively short cache (microsoft appears to cache indefinately).

**Comment by moudsen** [comment]
The direct linking could become possible when I've detached the Graph code from the main mailGraph package as will happen in v2.x, but would require a CDN (content distribution network) type caching.

In version 1.x this was a principal design choice exactly for the reason you are pointing out: "trusted URLs". In many occassions the Zabbix system is inside the Enterprise/local network and no direct external access is available.

As such I decided to include the graphs in the mail to fixate in time (to preserve perhaps for future reference even when the data is no longer available while underneath the message there is the possibility to have a persistent link to the actual data (Graph link).

If more users of mailGraph would support this request I could consider this however it would also require come externally available cache system as well (and could overcomplicate the solution while having the data attached in the mail).

You can mimic your request though by fiddling with the template to not attach but link the graph. Happy to have a look at that in v2.x if you think that will match your requirement better?

**Comment by moudsen** [comment]
Decided to close since long time no response received. The idea of keep the mail as tiny as possible and use externally cached/stored images would be possible with the concept of mailGraph as it actually stores in the /images directory however in a large production environment this could lead to potential high volume situations where, if retention is for example 1 year, the associated storage would need to grow exponentially in an uncontrolled way.
At the same time once images are sent along in an e-mail this a) does not need to retention images locally and b) gives the receiver the responsibility to retention on his/her own terms.
