### ISSUE TITLE
To verify that mailGraph v2.02 works in Zabbix 6.2.x

### ISSUE THREAD

**Issue by moudsen** [moudsen/mailGraph#32]
Now that Zabbix 6.2.x has been released mailGraph must be validated.

**Comment by kladderadeng** [comment]
I am just dipping into Zabbix and set up a brand new Zabbix 6.2.2 on Ubuntu Server 20 LTS. Today I implemented mailGraph and when trying to test the new Media type in the Web Interface, I receive the following error from Zabix:

`MailGraph notification failed : ReferenceError: identifier 'CurlHttpRequest' undefined`

According to [this Reddit post](https://www.reddit.com/r/zabbix/comments/vzi1az/telegram_webhook_not_working_in_zabbix_62/), it seems that CurlHttpRequest was removed and HttpRequest is now the way to got. I tried changing it in the Script, but there is more behind that than just using the new function :-(

Oh, and when using php mailGraph.php test, it works just fine for me. Is there a quick fix I can implement or does it require a complete rewrite of the code behind the Media type?

Edit: I got one step further by adjusting the function. It was mostly that the methods changed in upper / lower case style. But it still fails now with a JSON error
`MailGraph notification failed : SyntaxError: invalid json (at offset 1)`
and that is far beyond my knowledge of how to fix it ;-)

Edit2: I got it running! The json error was because my mailGraph Apache Site was not accessible yet and I received a 403 because of that. I probably missed that in the installation manual, but I had to chown root:www-data the mailGraph directory and chmod 775 the images, tmp and log directories, so apache was able to write to those.
In the Script code behind the media type, I changed from curlHttpRequest to HttpRequest and fixed a few methods that change upper / lower case. I know this is Git, but I am not sure if I can really contribute my changes or if it is wanted (it might break things for Zabbix versions older than 6.2.2), so I will try to include the code here, so you can see what was changed. I hope that helps. And thank you very much for sharing your code with us :-)

`
try {
    // Pickup parameters
    params = JSON.parse(value),
        req = new HttpRequest(),
        fields = {},
        resp = '',
        result = { tags: {} };

    // Set HTTP proxy if required
    if (typeof params.HTTPProxy === 'string' && params.HTTPProxy.trim() !== '') {
        req.setProxy(params.HTTPProxy);
        fields.HTTPProxy = params.HTTPProxy;
    }

    // Declare output type
    req.addHeader('Content-Type: application/json');

    // Must have fields
    fields.itemId = params.itemId;
    fields.eventId = params.eventId;
    fields.recipient = params.recipient;
    fields.baseURL = params.baseURL;
    fields.duration = params.duration;

    // Optional fields
    if (typeof params.graphWidth === 'string') { fields.graphWidth = params.graphWidth; }
    if (typeof params.graphHeight === 'string') { fields.graphHeight = params.graphHeight; }
    if (typeof params.subject === 'string') { fields.subject = params.subject; }
    if (typeof params.showLegend === 'string') { fields.showLegend = params.showLegend; }
    if (typeof params.periods === 'string') { fields.periods = params.periods; }
    if (typeof params.periods_headers === 'string') { fields.periods_headers = params.periods_headers; }
    if (typeof params.debug === 'string') { fields.debug = params.debug; }

    // Add generic fields
    Object.keys(params).forEach(function(key) {
        if (key.substring(0, 4) == 'info') {
            fields[key] = params[key];
        }
    });

    // Post information to the processing script
    Zabbix.Log(4, '[MailGraph Webhook] Sending request: ' + params.URL + '?' + JSON.stringify(fields));
    var resp = req.post(params.URL,JSON.stringify(fields));
    Zabbix.Log(4, '[Mailgraph Webhook] Receiving response:' + resp);

    // If there was an error, report it
    if (req.getStatus() != 200) { throw JSON.parse(resp).errors[0]; }

    // We expect the message id back from the processing script
    resp = JSON.parse(resp);
    result.tags.__message_id = resp.messageId;

    // Pass the result back to Zabbix
    return JSON.stringify(result);
}
catch (error)
{
    // In case something went wrong in the processing, pass the error back to Zabbix
    Zabbix.Log(127, 'MailGraph notification failed : '+error);
    throw 'MailGraph notification failed : '+error;
}
`

**Comment by moudsen** [comment]
Wow. I'm impressed with the discoveries done left and right. Unfortunately this also means that Zabbix has changed their interfaces without prior notification ... sigh. So far for backwards compatibility.

Anyway: I am VERY gratefull that you've shared your insights and I will incorporate these on short notice!

A "normal" way in Github would be to provision me with a pull from your end to merge with your new code, but in this case it requires some additional attention due to the object model change.

The only challenge I have now is to detect the exact version of Zabbix where their setup did actually change ... :-)

**Comment by kladderadeng** [comment]
Re: [moudsen/mailGraph] To verify that mailGraph v2.02 works in Zabbix 6.2.x (Issue #32)



Hi there!

Sorry for the delay! Thank you very much for your message, that really made me happy.
I am not really programmer (sysadmin for a few decades with a little bit of scripting experience), but the "fix" was pretty easy since it was just very minor changes and no real coding involved.
I was on the fence trying to fetch your code, commit the changes and make a pull request, but as you also write: The change might brake it for everyone using an older Zabbix version, so it is not really a good "fix".

I am happy that I got it running and I want to thank you for the hard work you put into this! It is a very nice addition to a tiny monitoring system that will sit at a remove location for weeks or months, and having the Graph information in the Mails for warnings is super useful :-)


Thanks again and have a great weekend!





Wow. I'm impressed with the discoveries done left and right. Unfortunately this also means that Zabbix has changed their interfaces without prior notification ... sigh. So far for backwards compatibility.
Anyway: I am VERY gratefull that you've shared your insights and I will incorporate these on short notice!
A "normal" way in Github would be to provision me with a pull from your end to merge with your new code, but in this case it requires some additional attention due to the object model change.
The only challenge I have now is to detect the exact version of Zabbix where their setup did actually change ... :-)

**Comment by moudsen** [comment]
Working on version separation as well as an installation script that will catch the Zabbix version and will configure the Media Type accordingly.

**Comment by moudsen** [comment]
Prepping for next release

**Comment by moudsen** [comment]
Final javascript update for 6.4+.
I've tested with Zabbix 5.4 and 6.0 LTS and works just fine so no split required in the code (anyone that needs an older version can pick up from the history of the repository :-)).

```
try {
    // Pickup parameters
    params = JSON.parse(value),
        req = new HttpRequest(),
        fields = {},
        resp = '',
        result = { tags: {} };

    // Set HTTP proxy if required
    if (typeof params.HTTPProxy === 'string' && params.HTTPProxy.trim() !== '') {
        req.setProxy(params.HTTPProxy);
        fields.HTTPProxy = params.HTTPProxy;
    }

    // Declare output type
    req.addHeader('Content-Type: application/json');

    // Must have fields
    fields.itemId = params.itemId;
    fields.eventId = params.eventId;
    fields.recipient = params.recipient;
    fields.baseURL = params.baseURL;
    fields.duration = params.duration;

    // Optional fields
    if (typeof params.graphWidth === 'string') { fields.graphWidth = params.graphWidth; }
    if (typeof params.graphHeight === 'string') { fields.graphHeight = params.graphHeight; }
    if (typeof params.subject === 'string') { fields.subject = params.subject; }
    if (typeof params.showLegend === 'string') { fields.showLegend = params.showLegend; }
    if (typeof params.periods === 'string') { fields.periods = params.periods; }
    if (typeof params.periods_headers === 'string') { fields.periods_headers = params.periods_headers; }
    if (typeof params.debug === 'string') { fields.debug = params.debug; }

    // Add generic fields
    Object.keys(params).forEach(function(key) {
        if (key.substring(0, 4) == 'info') {
            fields[key] = params[key];
        }
    });

    // Post information to the processing script
    Zabbix.Log(4, '[MailGraph Webhook] Sending request: ' + params.URL + '?' + JSON.stringify(fields));
    var resp = req.post(params.URL,JSON.stringify(fields));
    Zabbix.Log(4, '[Mailgraph Webhook] Receiving response:' + resp);

    // If there was an error, report it
    if (req.getStatus() != 200) { throw JSON.parse(resp).errors[0]; }

    // We expect the message id back from the processing script
    resp = JSON.parse(resp);
    result.tags.__message_id = resp.messageId;

    // Pass the result back to Zabbix
    return JSON.stringify(result);
}
catch (error)
{
    // In case something went wrong in the processing, pass the error back to Zabbix
    Zabbix.Log(127, 'MailGraph notification failed : '+error);
    throw 'MailGraph notification failed : '+error;
}
```

**Comment by moudsen** [comment]
Verified against Zabbix 5.4, 6.0 LTS and 6.4

**Comment by moudsen** [comment]
Releasing
